CREATE TABLE PORTFOLIO (
    PORTFOLIO_ID INT IDENTITY not null,
    BALANCE DOUBLE,
    VERSION INTEGER,
    PRIMARY KEY (PORTFOLIO_ID)
);
CREATE TABLE ACCOUNT (
    ACCOUNT_ID INT IDENTITY not null,
    ACCOUNT_TYPE CHARACTER(1),
    BALANCE DOUBLE,
    VERSION INTEGER,
    PORTFOLIO_ID INTEGER,
    PRIMARY KEY (ACCOUNT_ID)
);
ALTER TABLE ACCOUNT ADD CONSTRAINT ACCNT_PFOLIO_FK  FOREIGN KEY(PORTFOLIO_ID) REFERENCES PORTFOLIO(PORTFOLIO_ID);